version: '3.7'

services:
  owlify_api:
    build: .
    container_name: owlify_api
    ports:
      - '80:3333'
    environment:
      - NODE_ENV=production
      - DB_HOST=owlify_influx
      - PG_HOST=owlify_pg
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    volumes:
      - .:/home/api/
      - /home/api/node_modules
    depends_on:
      - owlify_pg
      - owlify_influx
    entrypoint: ["/docker-entrypoint.sh", "production"]

  owlify_pg:
    image: bitnami/postgresql:latest
    container_name: owlify_pg
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - postgres-data:/postgres/data

  owlify_influx:
    image: influxdb:1.8
    container_name: owlify_influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/influxdb/data

volumes:
  postgres-data: {}
  influxdb-data: {}
